### ISSUE TITLE
Auto detect changes when deploy a progrom

### ISSUE THREAD

**Issue by mojtabakaviani** [liara-cloud/liara-cli#20]
Please add capability that liara cli auto detect new or changed files instead upload all the files

**Comment by mhemrg** [comment]
Hey Mojtaba,
Thanks for your suggestion.

We had this feature in our previous version. But it had issues so we decided to remove it. Now we're planning to use a Git-based solution instead of our previous in-house solution.

Currently, I recommend upgrading to the latest version which is 2.8.3 using `npm i -g @liara/cli@2.8.3`. So then you can use .gitignore files to ignore unnecessary files. Or maybe you can use GitHub Actions or GitLab CI to automatically deploy your changes after each push. Using CI/CD would improve your deployments.

**Comment by mojtabakaviani** [comment]
we didn't decide yet to push sources to github or gitlab.

**Comment by mojtabakaviani** [comment]
Please use previous change detector for docker apps

**Comment by mhemrg** [comment]
Are you using `.gitignore` files to reduce your deployment size?
https://docs.liara.ir/app-features/ignore

**Comment by mojtabakaviani** [comment]
`.gitignore`  is for ignore files not need publish to host. not for detect changed or new files

**Comment by mojtabakaviani** [comment]
With new version upload files need long times and some time failed.

**Comment by mhemrg** [comment]
How much is your project's compressed size?

**Comment by mojtabakaviani** [comment]
I try use `.gitignore`, files upload to server but new changes not working.

**Comment by mhemrg** [comment]
You shouldn't ignore your code. Try to ignore huge files like photos and videos.

**Comment by mojtabakaviani** [comment]
if active previous change detector just for docker platform, it's very good. now must waiting to upload 10Mb every deployment.
